# Generated by Django 5.0.3 on 2024-03-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_cat_auction_description_auction_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='cat',
            new_name='category',
        ),
    ]
