# Generated by Django 5.0.3 on 2024-03-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_active_auction_bidder_alter_auction_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('ELEC', 'Electronics'), ('COMP', 'Computers'), ('SMH', 'Smart Home'), ('ARTS', 'Arts & Crafts'), ('AUTO', 'Automotive'), ('BABY', 'Baby'), ('BEAUTY', 'Beauty and Personal Care'), ('WOMEN', "Women's Fashion"), ('MEN', "Men's Fashion"), ('GIRLS', "Girl's Fashion"), ('BOYS', "Boy's Fashion"), ('HEALTH', 'Health and Household'), ('HOME', 'Home and Kitchen'), ('INDUSTRIAL', 'Industrial and Scientific'), ('LUGGAGE', 'Luggage'), ('MOVIES', 'Movies & Television'), ('PETS', 'Pet Supplies'), ('SOFTWARE', 'Software'), ('SPORTS', 'Sports and Outdoors'), ('TOOLS', 'Tools & Home Improvement'), ('TOYS', 'Toys and Games'), ('VIDEOGAMES', 'Video Games')], max_length=10),
        ),
    ]
