# Generated by Django 5.0.3 on 2024-04-06 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.AlterField(
            model_name='post',
            name='date2',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
