# Generated by Django 5.0.3 on 2024-04-06 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_post_date_alter_post_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date2',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
